const TASK_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  STARTED: 'STARTED',
  FINISHED: 'FINISHED',
};

const TASK_TYPE = {
  NORMAL_TASK: 'NORMAL_TASK',
  MANDATORY_TASK: 'MANDATORY_TASK',
};

module.exports = { TASK_STATUS, TASK_TYPE };
