export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_REPOS = 'GET_REPOS';
export const GET_POSTS = 'GET_POSTS';
export const POST_ERRORS = 'POST_ERRORS';

export const GET_ADMIN_PROJECTS_LIST = 'GET_ADMIN_PROJECTS_LIST';
export const GET_ADMIN_PROJECTS_LIST_ERROR = 'GET_ADMIN_PROJECTS_LIST_ERROR';
export const GET_ADMIN_PROJECT_DETAILS = 'GET_ADMIN_PROJECT_DETAILS';
export const GET_ADMIN_PROJECT_DETAILS_ERROR =
  'GET_ADMIN_PROJECT_DETAILS_ERROR';
export const UPDATE_ADMIN_PROJECT_DETAILS = 'UPDATE_ADMIN_PROJECT_DETAILS';
export const UPDATE_ADMIN_PROJECT_DETAILS_ERROR =
  'UPDATE_ADMIN_PROJECT_DETAILS_ERROR';
export const GET_ADMIN_PROJECT_TASKS_DETAILS =
  'GET_ADMIN_PROJECT_TASKS_DETAILS';
export const GET_ADMIN_PROJECT_TASKS_DETAILS_ERROR =
  'GET_ADMIN_PROJECT_TASKS_DETAILS_ERROR';
export const GET_ADMIN_USERS_LIST = 'GET_ADMIN_USERS_LIST';
export const GET_ADMIN_USERS_LIST_ERROR = 'GET_ADMIN_USERS_LIST_ERROR';
export const CLEAR_PROJECTS = 'CLEAR_PROJECTS';
export const CLEAR_PROJECTS_ERROR = 'CLEAR_PROJECTS_ERROR';
export const CREATE_NEW_PROJECT_ADMIN = 'CREATE_NEW_PROJECT_ADMIN';
export const CREATE_NEW_PROJECT_ADMIN_ERROR = 'CREATE_NEW_PROJECT_ADMIN_ERROR';
export const CREATE_NEW_TASK_ADMIN = 'CREATE_NEW_TASK_ADMIN';
export const CREATE_NEW_TASK_ADMIN_ERROR = 'CREATE_NEW_TASK_ADMIN_ERROR';

export const GET_ADMIN_TASKS_LIST = 'GET_ADMIN_TASKS_LIST';
export const GET_ADMIN_TASKS_LIST_ERROR = 'GET_ADMIN_TASKS_LIST_ERROR';
export const GET_ADMIN_CURRENT_TASK = 'GET_ADMIN_CURRENT_TASK';
export const GET_ADMIN_CURRENT_TASK_ERROR = 'GET_ADMIN_CURRENT_TASK_ERROR';
export const UPDATE_ADMIN_CURRENT_TASK = 'UPDATE_ADMIN_CURRENT_TASK';
export const UPDATE_ADMIN_CURRENT_TASK_ERROR =
  'UPDATE_ADMIN_CURRENT_TASK_ERROR';

export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR';

export const GET_USER_PROJECTS_LIST = 'GET_USER_PROJECTS_LIST';
export const GET_USER_PROJECTS_LIST_ERROR = 'GET_USER_PROJECTS_LIST_ERROR';
export const GET_USER_PROJECT_DETAILS = 'GET_USER_PROJECT_DETAILS';
export const GET_USER_PROJECT_DETAILS_ERROR = 'GET_USER_PROJECT_DETAILS_ERROR';
export const GET_USER_PROJECT_TASK_LIST = 'GET_USER_PROJECT_TASK_LIST';
export const GET_USER_PROJECT_TASK_LIST_ERROR =
  'GET_USER_PROJECT_TASK_LIST_ERROR';
export const GET_USER_CURRENT_TASK = 'GET_USER_CURRENT_TASK';
export const GET_USER_CURRENT_TASK_ERROR = 'GET_USER_CURRENT_TASK_ERROR';
export const START_USER_TASK = 'START_USER_TASK_ERROR';
export const START_USER_TASK_ERROR = 'START_USER_TASK_ERROR';

export const FINISH_USER_TASK = 'FINISH_USER_TASK';
export const FINISH_USER_TASK_ERROR = 'FINISH_USER_TASK_ERROR';
